# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jaccard_coeff <- function(R_idx, R_weight) {
    .Call('_monocle_jaccard_coeff', PACKAGE = 'monocle', R_idx, R_weight)
}

select_landmarks <- function(R_data, R_indices, R_indptr, R_n, R_dim, R_count) {
    .Call('_monocle_select_landmarks', PACKAGE = 'monocle', R_data, R_indices, R_indptr, R_n, R_dim, R_count)
}

